
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gabri
 */
public class TelaCurriculo extends javax.swing.JFrame {

    /**
     * Creates new form TelaCurriculo
     */
    public int libera = 0;
    public int libera2 = 0;
    
    public TelaCurriculo() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cxM = new javax.swing.JCheckBox();
        cxF = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        cx1Ano = new javax.swing.JCheckBox();
        cx2_5anos = new javax.swing.JCheckBox();
        cxMaior5 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        cxCSharp = new javax.swing.JCheckBox();
        cxCobol = new javax.swing.JCheckBox();
        cxJava = new javax.swing.JCheckBox();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRetorno = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("NOME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("E-MAIL");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("SEXO");

        cxM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxM.setText("MASCULINO");
        cxM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxMActionPerformed(evt);
            }
        });

        cxF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxF.setText("FEMININO");
        cxF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("EXPERIÊNCIA");

        cx1Ano.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cx1Ano.setText("1 ANO");
        cx1Ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx1AnoActionPerformed(evt);
            }
        });

        cx2_5anos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cx2_5anos.setText("2 a 5 ANOS");
        cx2_5anos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cx2_5anosActionPerformed(evt);
            }
        });

        cxMaior5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxMaior5.setText("MAIS DE 5 ANOS");
        cxMaior5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxMaior5ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("HABILIDADES");

        cxCSharp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxCSharp.setText("C#");

        cxCobol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxCobol.setText("COBOL");

        cxJava.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxJava.setText("JAVA");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnEnviar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEnviar.setText("ENVIAR");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        txtRetorno.setEditable(false);
        txtRetorno.setBackground(new java.awt.Color(240, 240, 240));
        txtRetorno.setColumns(20);
        txtRetorno.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtRetorno.setRows(5);
        txtRetorno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtRetorno.setEnabled(false);
        jScrollPane1.setViewportView(txtRetorno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cxM)
                                .addGap(40, 40, 40)
                                .addComponent(cxF))
                            .addComponent(txtNome)
                            .addComponent(txtEmail)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cx1Ano)
                                    .addComponent(cxCSharp))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cx2_5anos)
                                            .addComponent(cxCobol))
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cxJava)
                                            .addComponent(cxMaior5)))
                                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtNome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtEmail)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxM)
                    .addComponent(cxF))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cx1Ano)
                        .addComponent(cx2_5anos)
                        .addComponent(cxMaior5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxCSharp)
                    .addComponent(cxCobol)
                    .addComponent(cxJava))
                .addGap(18, 18, 18)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxMActionPerformed
        // TODO add your handling code here:
        cxF.setSelected(false);
        cxM.setSelected(true);
        this.setLibera(1);
    }//GEN-LAST:event_cxMActionPerformed

    private void cxFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxFActionPerformed
        // TODO add your handling code here:
        cxM.setSelected(false);
        cxF.setSelected(true);
        this.setLibera(1);
    }//GEN-LAST:event_cxFActionPerformed

    private void cx1AnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx1AnoActionPerformed
        // TODO add your handling code here:
        cx2_5anos.setSelected(false);
        cxMaior5.setSelected(false);
        cx1Ano.setSelected(true);
        this.setLibera2(1);
    }//GEN-LAST:event_cx1AnoActionPerformed

    private void cx2_5anosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cx2_5anosActionPerformed
        // TODO add your handling code here:
        cx1Ano.setSelected(false);
        cxMaior5.setSelected(false);
         cx2_5anos.setSelected(true);
         this.setLibera2(1);
    }//GEN-LAST:event_cx2_5anosActionPerformed

    private void cxMaior5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxMaior5ActionPerformed
        // TODO add your handling code here:
        cx1Ano.setSelected(false);
        cx2_5anos.setSelected(false);
        cxMaior5.setSelected(true);
        this.setLibera2(1);
    }//GEN-LAST:event_cxMaior5ActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        if(txtNome.getText().equals("") || txtEmail.getText().equals("") || this.getLibera() == 0 || this.getLibera2() == 0)
        {
            JOptionPane.showMessageDialog(null, "EXISTE CAMPOS NÃO PREENCHIDOS");
        }
        else
        {
            String sexo = "";
            String experiencia = "";
            String habilidade1 = "";
            String habilidade2 = "";
            String habilidade3 = "";
            
            if(cxF.isSelected())
            {
                sexo = "F";
            }
            if(cxM.isSelected())
            {
                sexo = "M";
            }
            
            
            
            if(cx1Ano.isSelected())
            {
                experiencia = cx1Ano.getText();
            }
            if(cx2_5anos.isSelected())
            {
                experiencia = cx2_5anos.getText();
            }
            if(cxMaior5.isSelected())
            {
                experiencia = cxMaior5.getText();
            }
            
            
            if(cxCSharp.isSelected() == false && cxCobol.isSelected() == false && cxJava.isSelected() == false  )
            {
                habilidade1 = "SEM HABILIDADE";
            }
            
            if(cxCSharp.isSelected())
            {
                habilidade1 = cxCSharp.getText();
            }
            
            if(cxCobol.isSelected())
            {
                habilidade2 = cxCobol.getText();
            }
            
            if(cxJava.isSelected())
            {
                habilidade3 = cxJava.getText();
            }
            
            
            
            txtRetorno.setText("NOME: " +txtNome.getText().toUpperCase() 
                               +"\n\nE-MAIL: " + txtEmail.getText().toUpperCase() 
                               + "\n\nSEXO: " + sexo 
                               + "\n\nEXPERIÊNCIA: " + experiencia.toUpperCase() 
                               + "\n\nHABILIDADES: " + habilidade1.toUpperCase() + " " + habilidade2.toUpperCase() + " " + habilidade3.toUpperCase());
            
            txtRetorno.setVisible(true);
            
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCurriculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCurriculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCurriculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCurriculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCurriculo().setVisible(true);
            }
        });
    }

    public int getLibera() {
        return libera;
    }

    public void setLibera(int libera) {
        this.libera = libera;
    }

    public int getLibera2() {
        return libera2;
    }

    public void setLibera2(int libera2) {
        this.libera2 = libera2;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JCheckBox cx1Ano;
    private javax.swing.JCheckBox cx2_5anos;
    private javax.swing.JCheckBox cxCSharp;
    private javax.swing.JCheckBox cxCobol;
    private javax.swing.JCheckBox cxF;
    private javax.swing.JCheckBox cxJava;
    private javax.swing.JCheckBox cxM;
    private javax.swing.JCheckBox cxMaior5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextArea txtRetorno;
    // End of variables declaration//GEN-END:variables
}
