
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gabri
 */
public class TelaJogoAzar extends javax.swing.JFrame {

    /**
     * Creates new form TelaJogoAzar
     */
    public int contJogador1 = 0;
    public int contJogador2 = 0;
    
    public TelaJogoAzar() {
        initComponents();
        lblAcertos1.setVisible(false);
        lblAcertos2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNome2 = new javax.swing.JTextField();
        txtAposta1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAposta2 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        lblAcertos1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblAcertos2 = new javax.swing.JLabel();
        btnJogar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("NOME");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder("JOGADOR 1"));

        txtNome1.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("NOME");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder("JOGADOR 2"));

        txtNome2.setEnabled(false);

        txtAposta1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAposta1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 6, 1));
        txtAposta1.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("APOSTA");
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder("JOGADOR 1"));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("APOSTA");
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder("JOGADOR 2"));

        txtAposta2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAposta2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 6, 1));
        txtAposta2.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("ACERTOS");
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder("JOGADOR 1"));

        lblAcertos1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAcertos1.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("ACERTOS");
        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder("JOGADOR 2"));

        lblAcertos2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAcertos2.setText("jLabel8");

        btnJogar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnJogar.setText("JOGAR");
        btnJogar.setEnabled(false);
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });

        btnFinalizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFinalizar.setText("FINALIZAR JOGO");
        btnFinalizar.setEnabled(false);
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnNovo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNovo.setText("NOVO JOGO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNome1)
                                .addComponent(txtNome2, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAposta1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAcertos1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lblAcertos2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(txtAposta2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAposta1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtAposta2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnFinalizar)
                    .addComponent(btnJogar))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAcertos1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(lblAcertos2)))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        // TODO add your handling code here:
        
        if(txtNome1.getText().equals("") || txtNome2.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"CAMPO NÃO PREENCHIDO");
        }
        else
        {
            btnFinalizar.setEnabled(true);
            
            int numero;
            int apostaJogador1 = Integer.parseInt(txtAposta1.getValue().toString());
            int apostaJogador2 = Integer.parseInt(txtAposta2.getValue().toString());
            
            
            
            numero = (int)(Math.random() * (6 + 1 - 1)+1);
            
            System.out.println(numero);
            
            if(numero == apostaJogador1)
            {
                JOptionPane.showMessageDialog(null, "O JOGADOR 1 ACERTOU");
                this.setContJogador1(getContJogador1() + 1);
            }
            else
            {
                if(numero == apostaJogador2)
                {
                    JOptionPane.showMessageDialog(null, "O JOGADOR 2 ACERTOU");
                    this.setContJogador2(getContJogador2() + 1);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "NENHUM JOGADOR ACERTOU | NÚMERO SORTEADOR : " + numero);
                }
            }
        }
        
        
        
    }//GEN-LAST:event_btnJogarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        
        lblAcertos1.setText(String.format("%d", getContJogador1()));
        lblAcertos2.setText(String.format("%d", getContJogador2()));
        
        txtNome1.setText("");
        txtNome1.setEnabled(false);
        
        txtNome2.setText("");
        txtNome2.setEnabled(false);
        
        txtAposta1.setValue(1);
        txtAposta1.setEnabled(false);
        
        txtAposta2.setValue(1);
        txtAposta2.setEnabled(false);
        
        btnJogar.setEnabled(false);
        btnFinalizar.setEnabled(false);
        btnNovo.setEnabled(true);
        
        lblAcertos1.setVisible(true);
        lblAcertos2.setVisible(true);
        
        
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        
         lblAcertos1.setVisible(false);
         lblAcertos2.setVisible(false);
        
        this.setContJogador1(0);
        this.setContJogador2(0);
        
         txtNome1.setEnabled(true);
         txtNome2.setEnabled(true);
         txtAposta1.setEnabled(true);
         txtAposta2.setEnabled(true);
          btnJogar.setEnabled(true);
          btnNovo.setEnabled(false);
    }//GEN-LAST:event_btnNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogoAzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogoAzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogoAzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogoAzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogoAzar().setVisible(true);
            }
        });
    }

    public int getContJogador1() {
        return contJogador1;
    }

    public void setContJogador1(int contJogador1) {
        this.contJogador1 = contJogador1;
    }

    public int getContJogador2() {
        return contJogador2;
    }

    public void setContJogador2(int contJogador2) {
        this.contJogador2 = contJogador2;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnJogar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblAcertos1;
    private javax.swing.JLabel lblAcertos2;
    private javax.swing.JSpinner txtAposta1;
    private javax.swing.JSpinner txtAposta2;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtNome2;
    // End of variables declaration//GEN-END:variables
}
