
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gabri
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    int libera_vivo = 0;
    public NewJFrame() {
       criarComponentes();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cxVivo = new javax.swing.JCheckBox();
        cxTim = new javax.swing.JCheckBox();
        cxOi = new javax.swing.JCheckBox();
        cxClaro = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        rbVista = new javax.swing.JRadioButton();
        rb3Vezes = new javax.swing.JRadioButton();
        rb6Vezes = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cxBateria = new javax.swing.JCheckBox();
        cxCapa = new javax.swing.JCheckBox();
        cxFone = new javax.swing.JCheckBox();
        btnComprar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MODELA A", "MODELO B", "MODELO C", "MODELO D" }));
        comboBox.setBorder(null);
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("MODELOS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("OPERADORA");

        cxVivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxVivo.setText("VIVO");
        cxVivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxVivoActionPerformed(evt);
            }
        });

        cxTim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxTim.setText("TIM");
        cxTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxTimActionPerformed(evt);
            }
        });

        cxOi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxOi.setText("OI");
        cxOi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxOiActionPerformed(evt);
            }
        });

        cxClaro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxClaro.setText("CLARO");
        cxClaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxClaroActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("PAGAMENTO");

        rbVista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbVista.setText("À VISTA");
        rbVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVistaActionPerformed(evt);
            }
        });

        rb3Vezes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb3Vezes.setText("EM 3 VEZES");
        rb3Vezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3VezesActionPerformed(evt);
            }
        });

        rb6Vezes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb6Vezes.setText("EM 6 VEZES");
        rb6Vezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6VezesActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ACESSÓRIOS");

        cxBateria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxBateria.setText("BATERIA ADICIONAL");

        cxCapa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxCapa.setText("CAPA");

        cxFone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxFone.setText("FONE DE OUVIDO");

        btnComprar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnComprar.setText("COMPRAR");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cxVivo)
                        .addGap(18, 18, 18)
                        .addComponent(cxTim)
                        .addGap(18, 18, 18)
                        .addComponent(cxOi)
                        .addGap(18, 18, 18)
                        .addComponent(cxClaro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbVista)
                        .addGap(18, 18, 18)
                        .addComponent(rb3Vezes)
                        .addGap(18, 18, 18)
                        .addComponent(rb6Vezes))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxBateria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxCapa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxFone))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cxVivo)
                    .addComponent(cxTim)
                    .addComponent(cxOi)
                    .addComponent(cxClaro))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbVista)
                    .addComponent(rb3Vezes)
                    .addComponent(rb6Vezes))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cxBateria)
                    .addComponent(cxCapa)
                    .addComponent(cxFone))
                .addGap(48, 48, 48)
                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxActionPerformed

    private void cxVivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxVivoActionPerformed
             
        
        if(cxTim.isSelected())
        {
            
            cxOi.setEnabled(false);
            cxClaro.setEnabled(false);
            
        }

        if(cxVivo.isSelected() == false && cxTim.isSelected())
        {
            cxOi.setEnabled(true);
            cxClaro.setEnabled(true);
            
            
        }
        
        if(cxOi.isSelected())
        {
            cxTim.setEnabled(false);
            cxClaro.setEnabled(false);
            
        }
        
        if(cxVivo.isSelected() == false && cxOi.isSelected() )
        {
            cxTim.setEnabled(true);
            cxClaro.setEnabled(true);
            
            
        }
        
        if(cxClaro.isSelected())
        {
            cxOi.setEnabled(false);
            cxTim.setEnabled(false);
            
        }
        
        if(cxVivo.isSelected() == false && cxClaro.isSelected())
        {
            cxOi.setEnabled(true);
            cxTim.setEnabled(true);
            
            
        }
      
        
        
        
        
    }//GEN-LAST:event_cxVivoActionPerformed

    private void cxTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxTimActionPerformed
        
        if(cxVivo.isSelected())
        {
            
            cxOi.setEnabled(false);
            cxClaro.setEnabled(false);
            
        }
        
         if(cxVivo.isSelected() && cxTim.isSelected() == false)
        {
            cxOi.setEnabled(true);
            cxClaro.setEnabled(true);
            
            
        }
         
        if(cxOi.isSelected())
        {
            cxVivo.setEnabled(false);
            cxClaro.setEnabled(false);
            
        }
        
        if(cxTim.isSelected() == false && cxOi.isSelected() )
        {
            cxVivo.setEnabled(true);
            cxClaro.setEnabled(true);
            
            
        }
         
        
        if(cxClaro.isSelected())
        {
            cxOi.setEnabled(false);
            cxVivo.setEnabled(false);
            
        }
        
        if(cxTim.isSelected() == false && cxClaro.isSelected())
        {
            cxOi.setEnabled(true);
            cxVivo.setEnabled(true);
            
            
        }
        
    }//GEN-LAST:event_cxTimActionPerformed

    private void cxOiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxOiActionPerformed
        // TODO add your handling code here:
        if(cxVivo.isSelected())
        {
            
            cxTim.setEnabled(false);
            cxClaro.setEnabled(false);
            
        }
        
         if(cxVivo.isSelected() && cxOi.isSelected() == false)
        {
            cxTim.setEnabled(true);
            cxClaro.setEnabled(true);
            
            
        }
         
        if(cxTim.isSelected())
        {
            cxVivo.setEnabled(false);
            cxClaro.setEnabled(false);
            
        }
        
        if(cxTim.isSelected() && cxOi.isSelected() == false )
        {
            cxVivo.setEnabled(true);
            cxClaro.setEnabled(true);
            
            
        }
         
        
        if(cxClaro.isSelected())
        {
            cxTim.setEnabled(false);
            cxVivo.setEnabled(false);
            
        }
        
        if(cxOi.isSelected() == false && cxClaro.isSelected())
        {
            cxTim.setEnabled(true);
            cxVivo.setEnabled(true);
            
            
        }
    }//GEN-LAST:event_cxOiActionPerformed

    private void cxClaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxClaroActionPerformed
        // TODO add your handling code here:
        if(cxVivo.isSelected())
        {
            
            cxTim.setEnabled(false);
            cxOi.setEnabled(false);
            
        }
        
         if(cxVivo.isSelected() && cxClaro.isSelected() == false)
        {
            cxTim.setEnabled(true);
            cxOi.setEnabled(true);
            
            
        }
         
        if(cxTim.isSelected())
        {
            cxVivo.setEnabled(false);
            cxOi.setEnabled(false);
            
        }
        
        if(cxTim.isSelected() && cxClaro.isSelected() == false )
        {
            cxVivo.setEnabled(true);
            cxOi.setEnabled(true);
            
            
        }
         
        
        if(cxOi.isSelected())
        {
            cxTim.setEnabled(false);
            cxVivo.setEnabled(false);
            
        }
        
        if(cxClaro.isSelected() == false && cxOi.isSelected())
        {
            cxTim.setEnabled(true);
            cxVivo.setEnabled(true);
            
            
        }
    }//GEN-LAST:event_cxClaroActionPerformed

    private void rbVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVistaActionPerformed
        // TODO add your handling code here:
        rb3Vezes.setSelected(false);
        rb6Vezes.setSelected(false);
    }//GEN-LAST:event_rbVistaActionPerformed

    private void rb3VezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3VezesActionPerformed
        // TODO add your handling code here:
        rbVista.setSelected(false);
        rb6Vezes.setSelected(false);
    }//GEN-LAST:event_rb3VezesActionPerformed

    private void rb6VezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6VezesActionPerformed
        // TODO add your handling code here:
        rb3Vezes.setSelected(false);
        rbVista.setSelected(false);
    }//GEN-LAST:event_rb6VezesActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
        String nomeModelo = comboBox.getSelectedItem().toString();
        String op1 = "";
        String op2 = "";
        int contador = 0;
        String pag = "";
        Double total = 0.00;
        double desconto;
        double parcela = 0.00;
        
        if(rbVista.isSelected() == false && rb3Vezes.isSelected() == false && rb6Vezes.isSelected() == false)
        {
            JOptionPane.showMessageDialog(null,"CAMPOS NÃO PREENCHIDOS");
            return;
        }
        
        if(comboBox.getSelectedIndex() == 0)
        {
            total = 1000.00;
        }
        
        else
        {
            if(comboBox.getSelectedIndex() == 1)
            {
                total = 1500.00;
            }
            else
            {
                if(comboBox.getSelectedIndex() == 2)
                {
                    total = 2000.00;
                }
                else
                {
                    if(comboBox.getSelectedIndex() == 3)
                    {
                        total = 2500.00;
                    }
                }
            }
        }
        
        if(cxBateria.isSelected())
        {
            total += 100.00;
        }
        else
        {
            if(cxCapa.isSelected())
            {
                total += 40.00;
            }
            else
            {
               if( cxFone.isSelected() )
               {
                   total += 30.00;
               }
            }
        }
        
        
        if(cxVivo.isSelected())
        {
            op1 = cxVivo.getText();
            contador++;
        }
        if(cxTim.isSelected())
        {
            if(contador == 0)
            {
                op1 = cxTim.getText();
                contador++;
            }
            else
            {
                op2 = cxTim.getText();
            }
        }
        
        if(cxClaro.isSelected())
        {
            if(contador == 0)
            {
                op1 = cxClaro.getText();
                contador++;
            }
            else
            {
                op2 = cxClaro.getText();
            }
        }
        
        if(cxOi.isSelected())
        {
            if(contador == 0)
            {
                op1 = cxOi.getText();
                contador++;
            }
            else
            {
                op2 = cxOi.getText();
            }
        }
        
        if(rbVista.isSelected())
        {
            pag = rbVista.getText();
            desconto = (total * 5) / 100;
            total = total - desconto;
        }
        else
        {
            if(rb3Vezes.isSelected())
            {
                pag = rb3Vezes.getText();
                parcela = total / 3;
            }
            else
            {
                pag = rb6Vezes.getText();
                parcela = total/3;
            }
        }
        
        enviarLog(nomeModelo , op1 , op2 , pag , total , parcela);
        
    }//GEN-LAST:event_btnComprarActionPerformed

    
    private void enviarLog(String nomeModelo , String op1 , String op2 , String pag ,Double total ,Double parcela)
    {
        model.addRow(
                        new Object[]
                        {
                            nomeModelo , op1 ,op2 , pag, total ,parcela
                        }
                    );
        
    }
    
    /**
     * @param args the command line arguments
     */
    private void criarComponentes()
    {
        
            comboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cxVivo = new javax.swing.JCheckBox();
        cxTim = new javax.swing.JCheckBox();
        cxOi = new javax.swing.JCheckBox();
        cxClaro = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        rbVista = new javax.swing.JRadioButton();
        rb3Vezes = new javax.swing.JRadioButton();
        rb6Vezes = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cxBateria = new javax.swing.JCheckBox();
        cxCapa = new javax.swing.JCheckBox();
        cxFone = new javax.swing.JCheckBox();
        btnComprar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MODELA A", "MODELO B", "MODELO C", "MODELO D" }));
        comboBox.setBorder(null);
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("MODELOS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("OPERADORA");

        cxVivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxVivo.setText("VIVO");
        cxVivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxVivoActionPerformed(evt);
            }
        });

        cxTim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxTim.setText("TIM");
        cxTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxTimActionPerformed(evt);
            }
        });

        cxOi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxOi.setText("OI");
        cxOi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxOiActionPerformed(evt);
            }
        });

        cxClaro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxClaro.setText("CLARO");
        cxClaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxClaroActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("PAGAMENTO");

        rbVista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbVista.setText("À VISTA");
        rbVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVistaActionPerformed(evt);
            }
        });

        rb3Vezes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb3Vezes.setText("EM 3 VEZES");
        rb3Vezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3VezesActionPerformed(evt);
            }
        });

        rb6Vezes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb6Vezes.setText("EM 6 VEZES");
        rb6Vezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6VezesActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ACESSÓRIOS");

        cxBateria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxBateria.setText("BATERIA ADICIONAL");

        cxCapa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxCapa.setText("CAPA");

        cxFone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxFone.setText("FONE DE OUVIDO");

        btnComprar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnComprar.setText("COMPRAR");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        model = new DefaultTableModel();

                jTable1 = new JTable(model);
                jTable1.setFillsViewportHeight(true);
  
                scrollProduto = new JScrollPane();
                scrollProduto.setViewportView(jTable1);
                
                model.addColumn("Nome");
                model.addColumn("Operadora 1");
                model.addColumn("Operadora 2");
                model.addColumn("Pagamento");
                model.addColumn("Total");
                model.addColumn("Parcelas");
                jTable1.setEnabled(false);
            
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cxVivo)
                        .addGap(18, 18, 18)
                        .addComponent(cxTim)
                        .addGap(18, 18, 18)
                        .addComponent(cxOi)
                        .addGap(18, 18, 18)
                        .addComponent(cxClaro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbVista)
                        .addGap(18, 18, 18)
                        .addComponent(rb3Vezes)
                        .addGap(18, 18, 18)
                        .addComponent(rb6Vezes))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxBateria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxCapa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxFone))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cxVivo)
                    .addComponent(cxTim)
                    .addComponent(cxOi)
                    .addComponent(cxClaro))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbVista)
                    .addComponent(rb3Vezes)
                    .addComponent(rb6Vezes))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cxBateria)
                    .addComponent(cxCapa)
                    .addComponent(cxFone))
                .addGap(48, 48, 48)
                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
        
        
    }// </editor-fold>                        
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
     private JTable table;
        private DefaultTableModel model;
        private JScrollPane scrollProduto;
        private JPanel panel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JCheckBox cxBateria;
    private javax.swing.JCheckBox cxCapa;
    private javax.swing.JCheckBox cxClaro;
    private javax.swing.JCheckBox cxFone;
    private javax.swing.JCheckBox cxOi;
    private javax.swing.JCheckBox cxTim;
    private javax.swing.JCheckBox cxVivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rb3Vezes;
    private javax.swing.JRadioButton rb6Vezes;
    private javax.swing.JRadioButton rbVista;
    // End of variables declaration//GEN-END:variables
}
